server:
  port: 8081

spring:
  application:
    name: task-manager
  main:
    web-application-type: reactive
  datasource:
    url: jdbc:postgresql://localhost:5432/TaskManagerDB
    username: root
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
      cache:
        time-to-live: 10s
    prometheus:
        enabled: true

